[package]
name = "gjoll-relay-server-rs"
version = "0.1.0"
authors = ["Tanner Rogalsky <tanner@tannerrogalsky.com>"]
edition = "2018"

[dependencies]
ws = "0.8.1"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0"
redis = "0.10.0"